piVersion: v1
kind: ConfigMap
metadata:
  name: server-map
data:
  httpd.conf: |-
    ServerRoot "/usr/local/apache2"

    Listen 5000

    LoadModule mpm_event_module modules/mod_mpm_event.so

    LoadModule authn_file_module modules/mod_authn_file.so

    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so

    LoadModule authz_core_module modules/mod_authz_core.so

    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so

    LoadModule reqtimeout_module modules/mod_reqtimeout.so

    LoadModule filter_module modules/mod_filter.so

    LoadModule mime_module modules/mod_mime.so

    LoadModule log_config_module modules/mod_log_config.so

    LoadModule env_module modules/mod_env.so

    LoadModule headers_module modules/mod_headers.so

    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so

    LoadModule unixd_module modules/mod_unixd.so

    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so

    <IfModule !mpm_prefork_module>

    </IfModule>
    <IfModule mpm_prefork_module>

    </IfModule>

    LoadModule dir_module modules/mod_dir.so

    LoadModule alias_module modules/mod_alias.so


    <IfModule unixd_module>

    User daemon
    Group daemon

    </IfModule>


    ServerAdmin you@example.com


    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">

        Options Indexes FollowSymLinks


        AllowOverride None

        Require all granted
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">

    ErrorLog /proc/self/fd/2

    LogLevel warn

    <IfModule log_config_module>

        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common

        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>

        CustomLog /proc/self/fd/1 common
    </IfModule>

    <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
    </IfModule>

    <IfModule cgid_module>
    </IfModule>

    <Directory "/usr/local/apache2/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>

    <IfModule headers_module>
        RequestHeader unset Proxy early
    </IfModule>


    <IfModule mime_module>
        TypesConfig conf/mime.types

        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz

    </IfModule>


    <IfModule proxy_html_module>
    Include conf/extra/proxy-html.conf
    </IfModule>

    <IfModule ssl_module>
    SSLRandomSeed startup builtin
    SSLRandomSeed connect builtin
    </IfModule>



---
apiVersion: v1
kind: Pod
metadata:
  name: pods-juan
  labels:
    app: mc3
spec:
  containers:
  - name: webapp
    image: httpd:2.4
    volumeMounts:
    - name: index-configdos
      mountPath: /usr/local/apache2/htdocs/index.html
      subPath: indexdos.html
  - name: webappdos
    image: httpd:2.4
    volumeMounts:
    - name: server-config
      mountPath: /usr/local/apache2/conf/httpd.conf
      subPath: httpd.conf
    - name: index-config
      mountPath: /usr/local/apache2/htdocs/index.html
      subPath: index.html
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 81
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: config-map
  - name: server-config
    configMap:
      name: server-map
  - name: index-config
    configMap:
      name: index
  - name: index-configdos
    configMap:
      name: indexdos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream webapp {
            server 127.0.0.1;
            server {
            listen 81;
            listen [::]:81 ipv6only=on default_server;

            location / {
                proxy_pass         http://localhost:5000;
            }
            location /please {
                proxy_pass         http://localhost:80/index.html;
                proxy_redirect     off;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mc3
  name: service2
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: mc3
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}